### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jamestalmage**
Eliminating some unnecessary cruft.

### CODE REVIEW

**Comment by jamestalmage** [comment]
@olalonde - can you kill the coveralls comments. It's in settings somewhere on coveralls.io. It's not needed anymore, since coverage status is displayed using the build status API.

**Comment by olalonde** [comment]
@jamestalmage sure

**Comment by olalonde** [comment]
Are you sure I'm the one who enabled it? Coveralls.io doesn't seem to recognise my GH account.

**Comment by olalonde** [comment]
Ok, I unchecked the `LEAVE COMMENTS?  ` box in coveralls.io

**Comment by RubenVerborgh** [comment]
I'm not sure about the added value of `isRedirect`/`mapObj`/`objectAssign`. They double the number of dependencies without adding significant value.

**Comment by RubenVerborgh** [comment]
This PR has become obsolete because of the object-oriented rewrite of 6b616824883a242342d52b4886d48ea83494e670.

**Pull request closed without merging**
